name: Daily Mastodon Post

on:
  push:
    branches:
      - develop
  workflow_dispatch:  # 手動実行ボタンの表示
  schedule:
    - cron: '0 0 * * *'   # JST 09:00（朝の通勤・通学時間帯）
    - cron: '0 5 * * *'   # JST 14:00（昼休み）
    - cron: '0 9 * * *'   # JST 18:00（帰宅直前）
    - cron: '0 12 * * *'  # JST 21:00（SNS閲覧が活発な時間）
    - cron: '0 14 * * *'  # JST 23:00（夜のリラックスタイム）

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install Mastodon.py
          pip install openai

      - name: Run bot script
        env:
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python post_now.py
